# Generated by Django 5.2.10 on 2026-01-29 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('title', models.TextField()),
                ('version', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnosis Categories',
                'ordering': ['version', 'code'],
                'indexes': [models.Index(fields=['version', 'code'], name='diagnosis_d_version_d4bfd6_idx')],
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DiagnosisCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_code', models.CharField(db_index=True, max_length=20)),
                ('full_code', models.CharField(db_index=True, max_length=20)),
                ('abbreviated_description', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('version', models.CharField(db_index=True, max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_codes', to='diagnosis.diagnosiscategory')),
            ],
            options={
                'verbose_name_plural': 'Diagnosis Codes',
                'ordering': ['version', 'full_code'],
                'indexes': [models.Index(fields=['version', 'full_code'], name='diagnosis_d_version_e39398_idx'), models.Index(fields=['version', 'is_active'], name='diagnosis_d_version_3bb844_idx'), models.Index(fields=['category', 'version'], name='diagnosis_d_categor_7a0547_idx')],
                'unique_together': {('full_code', 'version')},
            },
        ),
    ]
