# Generated by Django 5.2.10 on 2026-01-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosiscategory',
            options={'ordering': ['icd_version', 'code'], 'verbose_name_plural': 'Diagnosis Categories'},
        ),
        migrations.AlterModelOptions(
            name='diagnosiscode',
            options={'ordering': ['icd_version', 'full_code'], 'verbose_name_plural': 'Diagnosis Codes'},
        ),
        migrations.RemoveIndex(
            model_name='diagnosiscategory',
            name='diagnosis_d_version_d4bfd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='diagnosiscode',
            name='diagnosis_d_version_e39398_idx',
        ),
        migrations.RemoveIndex(
            model_name='diagnosiscode',
            name='diagnosis_d_version_3bb844_idx',
        ),
        migrations.RemoveIndex(
            model_name='diagnosiscode',
            name='diagnosis_d_categor_7a0547_idx',
        ),
        migrations.RenameField(
            model_name='diagnosiscategory',
            old_name='version',
            new_name='icd_version',
        ),
        migrations.RenameField(
            model_name='diagnosiscode',
            old_name='version',
            new_name='icd_version',
        ),
        migrations.AlterUniqueTogether(
            name='diagnosiscategory',
            unique_together={('code', 'icd_version')},
        ),
        migrations.AlterField(
            model_name='diagnosiscategory',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosiscode',
            unique_together={('full_code', 'icd_version')},
        ),
        migrations.AddIndex(
            model_name='diagnosiscategory',
            index=models.Index(fields=['icd_version', 'code'], name='diagnosis_d_icd_ver_d748c7_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosiscode',
            index=models.Index(fields=['icd_version', 'full_code'], name='diagnosis_d_icd_ver_7a8a83_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosiscode',
            index=models.Index(fields=['icd_version', 'is_active'], name='diagnosis_d_icd_ver_612fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosiscode',
            index=models.Index(fields=['category', 'icd_version'], name='diagnosis_d_categor_6ed690_idx'),
        ),
    ]
